### ISSUE TITLE
androidTargetSdk typo

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_external_MicroGUiTools#6]
@mar-v-in: [Here](https://github.com/microg/android_external_MicroGUiTools/blob/master/build.gradle#L34) you set androidTargetSdk to 23 while androidCompileSdk is set to 25, probably a typo.

**Comment by mar-v-in** [comment]
It's intentional and related to https://github.com/microg/android_packages_apps_GmsCore/issues/292 (which will receive a fix soon™). Don't ask why reducing the target sdk is a good idea, google just terribly failed...
